# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-21 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0008_folderpermission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='filer_folder_permission_users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
